### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(RISC_VISIM_APP)
add_subdirectory(RISC_VISIM_APPContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    RISC_VISIM_APP
    RISC_VISIM_APPContent
    QtQuickDesignerComponents)